// Auto-generated by scripts/sync-chat-error-code-dts.mjs
// Source of truth: shared/chat-error-code.js

export declare const CHAT_ERROR_CODES: readonly [
  "INVALID_REQUEST",
  "SESSION_NOT_FOUND",
  "MODE_SWITCH_FAILED",
  "FLEET_UNAVAILABLE",
  "FLEET_START_FAILED",
  "SEND_FAILED",
  "CREATE_SESSION_FAILED",
  "MODEL_LIST_FAILED",
  "TOOLS_LIST_FAILED",
  "SESSION_ERROR",
  "CLI_NOT_FOUND",
  "CLI_SPAWN_FAILED",
  "CLI_NOT_CONNECTED",
  "AUTH_REQUIRED",
  "UNKNOWN",
];

export type ChatErrorCode = (typeof CHAT_ERROR_CODES)[number];

export declare function isChatErrorCode(value: unknown): value is ChatErrorCode;
